# Generated by Django 3.2.22 on 2023-10-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=128, verbose_name='Descripción')),
                ('estado', models.CharField(max_length=128, verbose_name='Estado')),
                ('ciudad', models.CharField(max_length=128, verbose_name='Ciudad')),
                ('colonia', models.CharField(max_length=128, verbose_name='Colonia')),
                ('calle', models.CharField(max_length=128, verbose_name='Calle')),
                ('numero', models.IntegerField(default=0, verbose_name='Numero')),
                ('cp', models.IntegerField(default=0, verbose_name='Código Postal')),
                ('registrado', models.BooleanField(default=False, verbose_name='Ya existe')),
            ],
            options={
                'db_table': 'registro',
            },
        ),
    ]
