# Generated by Django 3.2.22 on 2023-10-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=128, verbose_name='Descripción')),
                ('estado', models.CharField(max_length=128, verbose_name='Estado')),
                ('ciudad', models.CharField(max_length=128, verbose_name='Ciudad')),
                ('colonia', models.CharField(max_length=128, verbose_name='Colonia')),
                ('calle', models.CharField(max_length=128, verbose_name='Calle')),
                ('numero', models.IntegerField(default=0, verbose_name='Numero')),
                ('cp', models.IntegerField(default=0, verbose_name='Código Postal')),
                ('registrado', models.BooleanField(default=False, verbose_name='Ya existe')),
                ('imagen', models.ImageField(upload_to='imagenes/', verbose_name='Imagen')),
            ],
            options={
                'db_table': 'registro_registro',
            },
        ),
        migrations.DeleteModel(
            name='registro',
        ),
    ]
