# Generated by Django 3.2.22 on 2023-10-19 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20231018_1857'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formulario',
            table='formulario',
        ),
    ]
