# Generated by Django 3.2.22 on 2023-11-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_formulario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
