# Generated by Django 3.2.22 on 2023-11-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_formulario_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, verbose_name='usuario')),
                ('email', models.EmailField(max_length=128, verbose_name='email')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
