# Generated by Django 3.2.22 on 2023-11-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='imagen',
        ),
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('nameId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.formulario', verbose_name='Usuario')),
                ('usuarioId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.usuario', verbose_name='Usuario')),
            ],
            options={
                'db_table': 'Likes',
            },
        ),
    ]
