# Generated by Django 3.2.22 on 2023-11-13 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20231111_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='dislikes',
        ),
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislikes', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('nameId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.formulario', verbose_name='Usuario')),
                ('usuarioId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.usuario', verbose_name='Usuario')),
            ],
            options={
                'db_table': 'Dislikes',
            },
        ),
    ]
