# Generated by Django 3.2.22 on 2023-11-14 00:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20231113_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='imagen',
            field=models.ImageField(default=datetime.datetime(2023, 11, 14, 0, 37, 47, 727647, tzinfo=utc), upload_to='imagen'),
            preserve_default=False,
        ),
    ]
